### ISSUE TITLE
How does it work

### ISSUE THREAD

**Issue by daviddias** [diffcunha/crp-raytracer#1]
Hi @diffcunha ! Just checked [your talk at NodejsDublin](https://www.youtube.com/watch?v=dCU55FruSdc), very cool work, congratz!

I'm trying to make it work myself, and hopefully add my contribution by adding a pint of WebRTC to distribute the load. I've been looking at the code and it seems that the published version here is largely outdated, can you confirm?

What I'm exactly interested about is to know how you break the image into an array of JSON blobs that then can be processed using ray tracing function, so:
- How to break the image into parts
- How to call the raytracing function with each part
- How to tesselate the image back again 

Thank you :)

**Comment by pierreozoux** [comment]
I think the code is up to date.

The 3d scene is broken into different part [here](https://github.com/crp-nheiro/crp-raytracer/blob/master/index.js#L68:L78).
Then, these data are sent to crowdprocess.
So you can call raytracing function directly without crowdprocess. Look into `src/program.js`. You can call [render](https://github.com/crp-nheiro/crp-raytracer/blob/master/src/program.js#L472) with the [scene](https://github.com/crp-nheiro/crp-raytracer/blob/master/index.js#L30), and the [data](https://github.com/crp-nheiro/crp-raytracer/blob/master/index.js#L68:L78) array you just created in the loop.

Finally, the image is put back again inside the webapp, using `canvas`. The important part is [here](https://github.com/crp-nheiro/crp-raytracer-webapp/blob/master/app/scripts/main_browser.js#L257:L260).

Hope it's clear enough :) Good luck with WebRTC!

**Comment by daviddias** [comment]
Thank you :) This helped! 

I've a few more questions :). I'm trying to break every step into each own file, so I can decentralize and understand it better. Right now it 'does render' something, but it is all black :(

Example:
https://github.com/diasdavid/simple-raytracer/blob/master/runner.js

I've checked, the data/tasks array given by [prepare-tasks](https://github.com/diasdavid/simple-raytracer/blob/master/modules/prepare-tasks.js) is the same as in your code and also the scene is parser correctly, however, when I call the [`raytracer-engine/program.js`](https://github.com/diasdavid/simple-raytracer/blob/master/modules/raytracer-engine.js), the result is always an string of [`'AAAAAAAA....'`](https://raw.githubusercontent.com/diasdavid/simple-raytracer/master/out.txt) for each task.

Any clue why it is all black? Or why would the `raytracer-engine/program.js` return always `'AAAA...'` ?

**Comment by pierreozoux** [comment]
So each black square would return `AAAAA...`. Even if you wait until the end of the process, you don't receive any "colored" result?

If not, I wouldn't know how to help you like this.

I would advise to try to render a simple scene, that you know work with crp-raytracer. and then you send the full scene (without cutting it into small pieces) to render locally and see the result. I think it would be easier, try with just one little task that you know is not black :)

**Comment by diffcunha** [comment]
@diasdavid What scene are you trying to render? For instance, if you camera (eye) is pointing to a place without any light you will only get a black picture..

**Comment by daviddias** [comment]
I'm trying to render the examples/pokeball.rt without any change, it should render something not black right? I do wait for it to finish.

Using `crp-raytracer`, locally is not working completely because it is only using XMLHttpRequest()

Here is my results for pokeball (tasks + scene + raytraced results)
https://gist.github.com/diasdavid/ec1082a5993449cb7277

**Comment by diffcunha** [comment]
Yes it should. Try with reflect.rt and tell me what do you see.

**Comment by daviddias** [comment]
Something interesting has happen, if I do .stringify and .parse on top of the scene when passed to the raytracer engine (which I was passing it directly because I didn't need to do the .replace trick), I no longer have fill 'AAAAA', never the less, the .png is still black, but probably because I'm saving the .png in a wrong way?

Difference: https://github.com/diasdavid/simple-raytracer/blob/master/modules/raytracer-engine.js#L677

Results:
https://gist.github.com/diasdavid/678042a39c675a86e5c8

**Comment by diffcunha** [comment]
The results you sent look like something so you probably are :P

**Comment by daviddias** [comment]
ahaha nice :) Can you check this piece https://github.com/diasdavid/simple-raytracer/blob/master/runner.js#L38-L51

I not 100% aware of what is the exact patterm to grab this data and glue it together, I grabbed that logic from your old code: https://github.com/crp-nheiro/crp-raytracer/blob/master/runner.js#L28-L53 

![](http://www.openbooktoronto.com/sites/default/files/obt/illustrations/I%20have%20no%20idea.jpg)

**Comment by diffcunha** [comment]
Hahaha, yeah, that part can be tricky. It looks like you're doing it well, you should have a picture. I'll have to look at it with time, maybe later.

**Comment by daviddias** [comment]
Habemos pokebolas!

Thanks to @igorsoarez who found this detail: https://github.com/diasdavid/simple-raytracer/blob/master/modules/raytracer-engine.js#L647-L654

Any specific reason why the change to strings instead of arrays?

**Comment by diffcunha** [comment]
Well done! Do you mean the result var? For base64 encoding, I had an array of ints before. In terms on data transmission, using base64 strings increased 3x the speed of transmission.

**Comment by pierreozoux** [comment]
:clap:

**Comment by daviddias** [comment]
ah, so basically you encoded on the actual program and then decoded by yourself (since I didn't see the decoding part, didn't realize that was encoding, cool trick!

**Comment by diffcunha** [comment]
Yes, the encoding is to improve the data throughput so the decoding part is not on the rendering engine but on the node module, if I'm not wrong.

**Comment by daviddias** [comment]
@pierreozoux @diffcunha I'm trying to put it to work in the browser as you did in this example here:
https://github.com/diasdavid/simple-raytracer/tree/master/examples/browser

But my canvas foo is not strong yet, the raytracing works fine, I just need to fill the canvas element correctly. Can you give me some light on that?

Here is the browser code:
https://github.com/diasdavid/simple-raytracer/blob/master/examples/browser/app/js/index.js

**Comment by daviddias** [comment]
Basically, I need to understand how this works:
https://github.com/crp-nheiro/crp-raytracer-webapp/blob/master/app/scripts/main_browser.js#L220-L309

**Comment by diffcunha** [comment]
Hi David!

I was wondering today how your project is going. Sure, we are using requestAnimationFrame to periodically call the draw function who will draw what's in canvasImageData on the canvas. At the other end, that canvasImageData is being fed by the onmessage handler, which is called when you get a message from the web worker. Is there any part of the code you want me to comment on?

Cheers

**Comment by daviddias** [comment]
Aaaalmost there, I've to figure out to to display the image in a canvas element like you did, I've reached something -> https://cloudup.com/cWNKeevKyEo -> https://github.com/diasdavid/simple-raytracer/blob/master/examples/browser/app/js/index.js

I'm not 100% sure of what you did here:
https://github.com/crp-nheiro/crp-raytracer-webapp/blob/master/app/scripts/main_browser.js#L252-L297 and how that magic to glue the image together in a canvas element works.

Thank you :)

**Comment by daviddias** [comment]
So, using a lil bit of persistence, I've eventually managed!

https://cloudup.com/cTD0PixuwAN

PS: I've no idea why it is rotated :P

**Comment by diffcunha** [comment]
Almost there! Cool! I know that part can be tricky, it's probably rotated because you switched x coord with y coord. Just guessing ; )
